### ISSUE TITLE
No figuran los puntos de interes luego de revisar otras capas

### ISSUE THREAD

**Issue by asergiop21** [marcelobauza/congo#292]
No tengo puntos de interés en CBR y PRV, luego de revisar las otras capas. 
![WhatsApp Image 2021-03-17 at 10 16 26](https://user-images.githubusercontent.com/2211666/111474913-4f508880-870b-11eb-9c4a-e0a28d0fecb1.jpeg)

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/111734433-e545f980-8858-11eb-8ab0-1d5226b2d0e8.png)
